language: python
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install Flask
  - pip install requests
  - pip install pytest-flask
# command to run tests
script: pytest
